name: Publish Docker image (mtn)

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-22.04
    if: github.repository == 'tobitti0/misskey'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/misskeyio/misskey
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image tags
        run: |
          echo "FORMATTED_BRANCH_NAME=$(echo ${{ github.ref_name }} | sed -e 's/\//-/g' )" >> $GITHUB_ENV
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          labels: ${{ env.FORMATTED_BRANCH_NAME }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/misskey:mtn-buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/misskey:mtn-buildcache,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/misskey:${{ env.FORMATTED_BRANCH_NAME }}
